# extend:
#   ../../st_layout.yaml

main:
  rleg_joint_angle:
    legends:
      - { key: sh_qOut, id: [0-5] }
      - { key: RobotHardware0_q, id: [0-5] }

  lleg_joint_angle:
    legends:
      - { key: sh_qOut, id: [6-11] }
      - { key: RobotHardware0_q, id: [6-11] }

  right_foot_forceZ:
    legends:
      - { key: sh_rfsensorOut, id: [2] }
      - { key: RobotHardware0_rfsensor, id: [2] }
    newline: False

  left_foot_forceZ:
    legends:
      - { key: sh_lfsensorOut, id: [2] }
      - { key: RobotHardware0_lfsensor, id: [2] }
    newline: False

  imu_gsensor:
    legends:
      - { key: imu_gsensor, id: [0], label: x }
      - { key: imu_gsensor, id: [1], label: y }
      - { key: imu_gsensor, id: [2], label: z }
    newline: False

  imu_gyrometer:
    legends:
      - { key: imu_gyrometer, id: [0], label: x }
      - { key: imu_gyrometer, id: [1], label: y }
      - { key: imu_gyrometer, id: [2], label: z }

  # ZMP:
  #   legends:
  #     - { key: sh_zmpOut, id: [0,1] }
